# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grpcnc.SendSMSRequest" do
    optional :phone, :string, 1
    optional :text, :string, 2
  end
  add_message "grpcnc.SendSMSReply" do
    optional :error_code, :int64, 1
  end
end

module Grpcnc
  SendSMSRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpcnc.SendSMSRequest").msgclass
  SendSMSReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpcnc.SendSMSReply").msgclass
end
